name: Android Fastlane with GitHub Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6.10"
        bundler-cache: true
        working-directory: android

    - name: Build APK using Fastlane
      run: |
        bundle exec fastlane android build_release
      working-directory: android

    - name: Upload APK to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: android/app/build/outputs/apk/release/app-release.apk
        tag_name: release-${{ github.run_number }}
        name: "App Release #${{ github.run_number }}"
        body: "Automated release from main branch"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
